services:
    jekyll:
        image: jekyll/jekyll:4.2.0
        command: jekyll serve --force_polling --trace 
        platform: linux/amd64
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
            - jekyll_cache:/srv/jekyll/.jekyll-cache
volumes:
    jekyll_cache: